steps:
  # コンテナイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/calendar-slack-bot', '.']
  
  # コンテナイメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/calendar-slack-bot']
    # コンテナイメージをCloud Runにデプロイ（🚀 高速化設定）
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'calendar-slack-bot'
      - '--image=gcr.io/$PROJECT_ID/calendar-slack-bot'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      # 🚀 高速化: リソース設定
      - '--memory=1Gi'
      - '--cpu=2'
      - '--concurrency=100'
      - '--max-instances=10'
      # 🚀 高速化: タイムアウト設定
      - '--timeout=300'
      # 🚀 高速化: コールドスタート軽減（有料機能だが参考として）
      # - '--min-instances=1'  # 1つのインスタンスを常時起動（無料枠では使用不可）

# Cloud Loggingを使用してエラーを解決
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/calendar-slack-bot'