service: slack-calendar-bot

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  environment:
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_APP_TOKEN: ${env:SLACK_APP_TOKEN}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /slack/events
          method: post
      - http:
          path: /slack/events
          method: get